apiVersion: v1
kind: Secret
metadata:
    name: flux-system-git-auth
    namespace: flux-system
type: Opaque
data:
    username: ENC[AES256_GCM,data:CMGVV+zMrdsTUGFS,iv:0rgSlUzeKG6h1j3w1+ysqSRDa9ug6fGSYqqdE6phYYc=,tag:F3dm7pZuJyDG2xVqpOZQlw==,type:str]
    password: ENC[AES256_GCM,data:L87VRi9m/3cMKD3dag9NAolNX9NdWP730khJFKQEKnMtLEePUbs+Ofmdc8n0+zGNbAtlOy1WacU=,iv:QHxu7ZazMBmnXlhHXoyi3ybakPt4mggqyxBgB/SNoao=,tag:6d/6AYWCf34DwXzoMP1EBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUE5yZXAzMFZaaGNhLzZx
            Y3pINnkzanNKYWxoKzlnYUFPNWJnb2Y3N0YwCnhhV1Ezb2NTcVZnakt5QlN4N0wx
            QWRwWjJUaWF0ajhCRXRDS3hZbmxKSkkKLS0tIGpOdXJuUHdHT3NyN01hOGZ0WEow
            c3U2eXg5cENYMzkwTzQrUWQ4ZHpuUlkKOF7YYSIteQtwtRFs/KDJryduN6Rqu93d
            GfGH+BOynYDjSxPtyqcQZG3IbYjlio34rv0lyxd14plx1QVWdxrZ2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T15:23:18Z"
    mac: ENC[AES256_GCM,data:0fAsMPdpLF/hSrerKa0lUCVsbryyLy7n0KhMKCGnzWJLd/RoEeEBQOwOgEjc06o/K4MT5iwAtjLRWWNnwZdGgHh0nkNmOsBQ80vjHi8dhsMgBqhnBN7bTEG3FSh8s1z+YO/8tKHlWwYHCbXifJCNRr5SXu3HeYsj1xQSyf8Fl9o=,iv:OSHQf0Q4jgKB3RAbE7xtQIQ3uX67P6/HNpPlWpX0XmE=,tag:y3Cm2coT6CFJOunf4fVu5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
