apiVersion: v1
kind: Secret
metadata:
    name: ghcr-geohazardwatch
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:dAl6A3MMXjZmrPYfeJdn72vgSdM2DQq79pQe/3LiQLOXUyIbY1jQGSLrmVQDYB3h4V17bawhyAH3G4wD4c77/1y1j+UDAIORDspfuh9yqtz99TJdkrTlgeAcHtVRdGwObsBTOXoswIAQYGnm/KVMqmhlhe/Q5EvrxviSvenflJFqFkG6e3tGGGZncSdRkrdxSzz3GkkLHytrA4LSgQKqH1Q5ef0g5Jz2uVyXOwDomAUBiAXSaOW8lpA/Gwc6nqSqyVVBYbBltwNjlgvA46mek+iD4wSIMK7WNebD7nv/E/4qxMl3,iv:S7feSq+AwFs1A0YU4RipufMORPtppaOIAQlFIVMxhTE=,tag:g/N9YE7k74bt/lIOkYWizw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWE5tWitPRDVnR2JvTWU0
            TExBR2Y5MHhGdysycnFXdlQyYjJHc0ZQaDEwCnRnVFc2eE5KbE5tcDA2NThpTUYz
            MGV6OVZRby9OYXdaUW81QVdjWklxWUUKLS0tIE5JYjlaVnFhY1cxVmkwK1g5NDlo
            NXdZYk0rSHJnQzJkZ0wvWFFOT2N6QWsKR26Zk5lGjDj0Bi5UMM6ObVB+/nKHOz21
            OyLqnArxSOaTC/p8PpUu9MkHiedzPqTb3T4OaYfevzcSo1xy0kpH8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:15:29Z"
    mac: ENC[AES256_GCM,data:a3LZskH9dwDbGqCpFCO0zv+clzy22uhbpBDGF3PpaJp+s/e1UJLnuo6+dufP8yLnP898AVZGhjp4sjrSzoHPNZdrM6jb0fWWZG2215y+6BT1mJ3OS2g5DItLOas9wFtxuNuNPrh8GeAdcJ9a2CVHQb0HjNYsO1mI15bXn5OSNhI=,iv:d+dGF9TM/CUr7Xnjh5n0IK7PcVmImQwTsAGt2BRMSUw=,tag:rsAY/xojEn4J1zIUR/fLyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
