apiVersion: v1
kind: Secret
metadata:
    name: ghcr-geohazardwatch
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:lWFLG4E1LN8XnCJxC68RHJOVqEYNYbFw5lqfs1FMWnbN2eyD0pshMWcr2ubV+oBkRAGpeIdHKGuCaooe+dpMyxRbfQcfB+CiHcJKGI63bFgHntd6hFKNK89WxiGNpy0IhHh17r20AqJhWT9OtJobdxSg9PWHJyl9K3GVOOMp+/ZgGicPtCgz+g==,iv:0Lapt4+aPmoghY66qLwBbNvdSZLkazASLiMP8nycbHA=,tag:EcbB18nYOl7ug/UFyV5iXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUThxY3l2SkRVWUhuQjRv
            cUl4djVLOXl0R0dzQXQvWjh3MTdjdzJSWkFjCm1zYkprOGN5THVGeEFtd1pPbVZa
            YjYrY2hDZzVEK0loREtLT0JOZ0hBS1UKLS0tIFNKbzFOTHU1eWlxcEFiR2dpN3k4
            RGExdDdtc0F6SE9tQzZ2a2lNV1VxbTAKjCF5Fa8Reej8p23ImbYGj28r6gxzW8WL
            L6BA0P3BOQ2nbfAuFFOLrk7Td3vrUW939UqYlYu4QPQjELF7D8Ukjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T13:28:20Z"
    mac: ENC[AES256_GCM,data:OaO4cnX2oaddhWE6hwhzQxUHyl2uPPqA3rhn0S1LOj3g6C7sxdUHlyRYpKvTLL71yv63MdFQeTUV2PJG/mWIL8bTzwNE5OzaX9VCeVT3KYbo0go92+ifXFXlB6GcwITYl3/YB/05Fq0iO2+/WJfA9i3puXPBKxp5A36B/eTtImU=,iv:FEdIM8Y/f8i1WZAHyH0eVbS/ortfXULt+EdA8CZHMzs=,tag:skObAcodntfP+yMgK1xRqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
