apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-data
  namespace: openbao
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: openbao-data-pv
