apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  serviceName: "nextcloud-headless" # This should match the name of your headless service
  replicas: 1 # Start with 1 replica for initial setup, then scale up
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:28-apache # Use a specific version, not latest
          ports:
            - containerPort: 80 # Or 443 if you're using an image with built-in HTTPS
              name: http
          env:
            # Database connection details (replace with your actual values or use secrets)
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: database-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: database-password
            - name: MYSQL_HOST
              value: mariadb-headless # Or the service name of your database
            # Nextcloud specific environment variables
            # These can be patched in overlays for specific environments
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "your-nextcloud-domain.com" # Space-separated list of domains
            - name: NEXTCLOUD_UPDATE
              value: "1" # Allow automatic updates (can be disabled for manual control)
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html # Default data directory for Nextcloud
              subPath: html # If you want to store Nextcloud data in a subfolder of the PVC
      volumes:
        # If you are using a dedicated data volume for nextcloud
        # This is where your Nextcloud files will be stored.
        # This will be created by the volumeClaimTemplates below.
        # This volume is typically shared across replicas for Nextcloud,
        # often via an NFS or similar shared storage solution.
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc # This name should match the volumeClaimTemplates name
  volumeClaimTemplates:
    - metadata:
        name: nextcloud-data-pvc # This creates a PVC for each StatefulSet replica
      spec:
        accessModes: [ "ReadWriteMany" ] # "ReadWriteOnce" if using single-node, "ReadWriteMany" if shared storage like NFS
        storageClassName: standard # Or your specific StorageClass
        resources:
          requests:
            storage: 20Gi # Adjust as needed for your data