apiVersion: v1
kind: Secret
metadata:
    name: yourphr-relay
    namespace: yourphr
type: Opaque
stringData:
    YOURPHR_RELAY_SECRET: ENC[AES256_GCM,data:4uLIzx04TVTpqS/BaCWwu8LR+PfK4Gd0F8fn+ohobT1WRxS0tEvMekDiB14=,iv:kaxzwXpDCIRjNrjx00aCqHZEbCm+oOGcV/ed9R5QB1E=,tag:yrqGsPVrrpQp3Ie5c0I4ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZXBXSmZJUEgwUVUvbzFX
            dURxQUhBaUdic3VoQ3I3cHFnOE8wbGoyVVR3Ckd1dlh1aXNCQWo2WlBJM1ZlSEU5
            U3JVaFcyK2RHSm5YUkIrd0xFRGtycWMKLS0tIGpsWjZUNExvdXY0emp0cmJ3ZTVw
            VTk0ZUgwcEljK0ZqbTdvMlZTWFl5bUUK8tIo3TfFMxvQvbAcFxPS8cdeCC+LzT3z
            4Gk8wfX19JFtDO1KI3DUhgLdxCBEo4d+s/gR620PoQnSQYTLyJ36pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T09:36:22Z"
    mac: ENC[AES256_GCM,data:ZtCcqR64Hzc7nzcIPoeZ0seeZi0F2Fy4u+t29aJyxTPwx5sKL2mBrIXiKv15BUB5DfRqOqiPRBafHnreKiB/ifB8IOdIzqhTXGal0sEBbJzltZFsXT6hPL6yM9OptQG1IH862Ef2ktiZgjpV2QsTLjTg7N9FduVQPejOWz5zhVg=,iv:B3puEbOzeVzuhVS1xBM4fZPF8yL3C2zcCSI1XfGUapQ=,tag:BVu0PbIaBnY78M/7Zr0qJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
