apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yourphr-relay
  namespace: yourphr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: yourphr-relay
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: deby/yourphr/yourphr-relay
