apiVersion: v1
kind: Secret
metadata:
    name: maps-secret
    namespace: maps
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:2vobnP3I2apLw4NVoGC6siuG1LUIP79ONfQXdUIBBguvyHZaXm3cPpI1lDg=,iv:UOONBOvmafcckmNJ0Elt6T2OQDNajnVhuanbwEt2iQ8=,tag:gePGEk4l0lzki+kcKa9BrA==,type:str]
    secret-key-base: ENC[AES256_GCM,data:eDibUweqSlhlIPjv83u6N1N3a7qGbIpEWV2wB2ix0HExJPdBe5gSqeRISS7yV1wiD2ILVrSqn+RcrXVZ0dyg8jbF0W6Drv+gCYZtkNNQZwPD4UotA6cK3SsJCEOXoD4GFXmL7nEIxQTRyuoyQz79DFPb4IqFeq/LDUrqNhJmY1M=,iv:yAUZpPQQ/V4mDwPWJ0OpJ9F/5NropFUxhFEwM2z9mzQ=,tag:AFM6hlnMcu7xb3iJq+LXdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOFplRGpQUnd5cmJ0VTFI
            RkVVVSs4STlJa0lZOWtqU2R3dHFMQmNyQkRnCjljcjQyOTRJbXRHWHpuMVVuWnJk
            VVZNR0pBQ1JWTXBtNG0zTWpzdlZNbWcKLS0tIDFMOFhjdzBOZnFkR3czY3hNUnR6
            SktqYytvVWlvZE9lMTJ5R0FZa3hJTkUKTqPttyZ9p2hBrgw3uup3fsUZLhF/9PJs
            UgTagt+sCslRkfOWhW33EfOc9J8h3IeR4oSh8+nzU2Z9nHjqyjxfpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T20:16:35Z"
    mac: ENC[AES256_GCM,data:QkVp191o9Q5tcB+6j8K5zpCnUaCrzQMnNHvjcCDpBOjv1Rj6uN4c/dlGcm2FPvZShl7HcOgW2D3AURGh+o0dcfsbfaNm5aVNbW3sMYkx0ftQhYOsIbgAX2ZgHdS1Gx5qxoRJGgCaVhFkZUHfRPjemxC3R0+xjgQTeKaSXizo0c8=,iv:IoiakkA3zeyxuirDSwji4CyQvQ7NO/uvDjGNP4C/Khc=,tag:+2ykardQGUoBQmN4xGfe7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
