apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maps-app-data-pvc
  namespace: maps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: maps-app-data-pv
