apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maps-shared-pvc
  namespace: maps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: maps-shared-pv
