apiVersion: v1
kind: PersistentVolume
metadata:
  name: maps-db-pv
  labels:
    app: maps-db
    type: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/local-k3s-data/maps/db
    type: DirectoryOrCreate
