apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maps-secret
  namespace: maps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: maps-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: deby/maps/maps-secret
