apiVersion: v1
kind: PersistentVolume
metadata:
  name: maps-shared-pv
  labels:
    app: maps
    type: shared
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/local-k3s-data/maps/shared
    type: DirectoryOrCreate
