apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-cert
  namespace: home-assistant-proxy
spec:
  secretName: home-assistant-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - ha.nerdsbythehour.com
