apiVersion: v1
kind: Secret
metadata:
    name: demo-yourphr-relay
    namespace: demo-yourphr
type: Opaque
stringData:
    YOURPHR_RELAY_SECRET: ENC[AES256_GCM,data:VJyWueIaa7HAMKD65irys4GMNwPm5FlpBjkTJABc5aEi5Rt6Xi7CFpD1D3Q=,iv:u+pvuxxIylOwJWO8CbA3ZsqEHlPy8MYPOKvOHaWJEW8=,tag:DzJ/psceHCrI4MQOmPgaEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTHcvSWpWbUFyVndSSGV3
            MVlkYzZmUjB2NGdFbUpkS1E1bDEyRGVSSjNJClZRd29VZmhhUG9lb3JKY3I1QmJU
            WllkWE5jQUdtVEh0K3pKK1Nmak0xdU0KLS0tIFUwYnBaMUFYY3FDWUVNSzh4T2ps
            dHNHbGpkbVd0TThDNldUclZEeExERE0KsWkWZeZaSBKvGMCRwZYrQwQog45YmL6d
            opV5+IBtRHi90UF3MR3IzcLrOh1h5v4vVszsfQ9D/0F48K7GzIuSpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T12:10:53Z"
    mac: ENC[AES256_GCM,data:cO4wg475M7vK8xhWwoycqzISbcOSxp3GCX7v/yQR6VbCErZ/M+ZctJbJy82OcQPFUxxBubPGD+CqV7cPR0ywPomRmvMHA9GTg7ndO0DT7vedNszwLew/4em3Gn38uD/weRB5aGz2F+zCbLzQGRU1czdGcCyGhKRTVSw4qBK+DTo=,iv:0PvSso/h7ZESQg8u5lF9EMFeRD0OxXxXfWyIfvoXiyU=,tag:KP3bbX9XIP6C6c8enF+wQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
