apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-yourphr-relay
  namespace: demo-yourphr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: demo-yourphr-relay
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: deby/demo-yourphr/demo-yourphr-relay
