apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: messaging
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: mqtt
  selector:
    app: mosquitto
