apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fasten-data
  namespace: fasten
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
