apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: owntracks

resources:
  - namespace.yaml
  - recorder-pv.yaml
  - recorder-pvc.yaml
  - recorder-configmap.yaml
  - recorder-lua-hook-configmap.yaml
  - visual-configmap.yaml
  - recorder-deployment.yaml
  - recorder-service.yaml
  - recorder-basic-auth.sops.yaml
  - recorder-middleware.yaml
  - recorder-ingress.yaml
