apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owntracks-store-pvc
  namespace: owntracks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: owntracks-store-pv
