apiVersion: v1
kind: PersistentVolume
metadata:
  name: owntracks-store-pv
  labels:
    app: owntracks-recorder
    type: store
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/local-k3s-data/owntracks/store
    type: DirectoryOrCreate
