apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: owntracks-basic-auth
  namespace: owntracks
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: owntracks-basic-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: deby/owntracks/owntracks-basic-auth
