apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openspeedtest-tls
  namespace: guest-services
spec:
  secretName: openspeedtest-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - nerdsbythehour.com
