apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-yourphr-data
  namespace: demo-yourphr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: demo-yourphr-data-pv
