apiVersion: v1
kind: Secret
metadata:
    name: demo-yourphr-sandbox-credentials
    namespace: demo-yourphr
type: Opaque
stringData:
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_ID: ENC[AES256_GCM,data:+r6PDLUdmJaPV5TqcSoQoMTbe/4WefsCVBd9pfhyI8SorRIvjgD63A==,iv:yfQAqkc5xBG/Z277ILw8/6awnuowzlChmhS+DElqKzg=,tag:XaGhjnMIWA3qvIVK57idwQ==,type:str]
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_SECRET: ENC[AES256_GCM,data:snXOZ8/TWF2y3z7hMgx3oU9L9OIbpEz6RLWSMWwf0xWO9303kiOGLjPhFdkIPWaWxcUz2WuyDlh1CeWSylItayXL9WJfxTmuTzaXlg451g/eGiz8LzCHiES87ER5OFaKR/UgB0TtnCujOoJZQfy7XKIKeYxPtSAxU7a00EiXwvs=,iv:JpxKtH5OKmgbXmObpcEshGcxNm0zU+91VmqXxSJffJQ=,tag:qptE89lZJCWowZ1VW8vwMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdUYvNFNVWE9PUHZzQ1JF
            cEp5Y2JDbmVnckJXajZ2QmczUG90M3hsa2prClptT3JocGd2ZjM1blprVUE2MGV2
            SzZyMTlXeTlRU1lUTlQwcDQvazBQUTQKLS0tIHY5ZlRQbFdPNG9MeHFsUFhtanZ3
            M0VUZWVZV09tVDl3cWJveVkxeWhpYU0KvVySWaO6pAnmTBM6msYtHeI4/LG7/50y
            gKPZCCAi+aw0GTYvnWKnOaIllTGCAYusNScTXbGP/HWez2NJTpp+yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T12:44:46Z"
    mac: ENC[AES256_GCM,data:Zdt2A3LlOdvLbzpqnPe/bN4pgE9CTu4gBR6dZxoOBdPvSz/HSeabfgZ7i0irAHsh7AIe0HK5kTgyI2fcRX6bf+to+ecNYsF1ePCXrlAuyQRZSMK+IUISqo4pItuhUkQi5rfPYpQgiFm7K2bwk/qwLE01HNr4davlkUFzrhbUd88=,iv:LC1A6dIiVUch+qxOSN/BiYKFdEdp99X0Tdozc42lygQ=,tag:TfeSl9yT0ckLgGYT0iTOJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
