apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls
  namespace: guest-services
spec:
  secretName: whoami-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - deby.nerdsbythehour.com
