apiVersion: v1
data:
    postgresql_password: ENC[AES256_GCM,data:3ADFo/8rkWj+OfKF8uL2aTKwjFWdhmDbYxzEZD8V1YoVaB6WExyUYl3uzCY+UcX9jIYr79Ejp4+1+qeN0XfZMY9tyaQZsqaBcRuZ8w==,iv:eY5hg4bOb4eC0iu13KZyVeoeyx0/cmufWPFZ1aim788=,tag:07hMlTUfwtWprd1wNQKcmg==,type:str]
    secret_key: ENC[AES256_GCM,data:70Tt2YBd6qXdn3df67JnaLF9KT/DlW62EMbH6ZW/omSJvBogEJ6ucZairTx3MByaHqmCdYtjCPCkj50XfpIlvTv0D+eRBis8a1v5u6CLVMlozShtkBXYEMAqRKYnIz2SB7r7c9Dzc+R0sh1N,iv:NI1gHGQQQ22MZVpsbj6w/Viw+j52i9UOXBt9JaymQ8k=,tag:8aaZTLIw3V6f6hSQLPsEiQ==,type:str]
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOHljVkRoWEJxREdIQlAz
            azVOOG9xYzVqRGZOM3VQRjBNUnNNeFZjelJnCnl2ek5YbVBtMjBCY2F4bDlMM3BW
            aVkwbjRkNEI2TkcwMktxL1laMXJmNDAKLS0tIExrWDN2bWdSSGdpK2pLejNwcGpN
            V1V4UnZlWnhVVTFiUVgyOEhUNm5YcTAKaBOSgVe3CcahXy93cl9RKqZXI/sIQ3J7
            1s6Q6INqSWbWDh70fs83U9dqskIVLKyQf1h0rWgkfrC77DPjlEA7Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T14:37:51Z"
    mac: ENC[AES256_GCM,data:zmKS2TVvOidZlCtgt9Aoz1qohnCi7m6YMVWykOW088j6gnwkkhp2xbyIUfTqc+A9WJA6fn+i3bDbuk0KgfeFPnEIG+Hc1exguphYDs0i5BTlgirZALMz5P6lRjoaHvsrQbykH5bk/fhxjmwNvqKaSRnBd9/Aw2pVWoYI7v5HGMg=,iv:lff0C3puovdu6oPYpclljPkCeOXmLRklshax9uv+0yI=,tag:zSN+v3YF2Xk3IK3sFl+C8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
