apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: '2025.10.1'
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 12h
  # IMPORTANT: Secrets are stored in 'authentik-secrets' Secret (not in git)
  # Create manually: kubectl create secret generic authentik-secrets -n authentik \
  #   --from-literal=secret_key="<generated-key>" \
  #   --from-literal=postgresql_password="<generated-password>"
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgresql_password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgresql_password
      targetPath: postgresql.auth.password

  values:
    authentik:
      error_reporting:
        enabled: false

    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.nerdsbythehour.com
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.nerdsbythehour.com
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production

    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          size: 8Gi

    redis:
      enabled: true
      auth:
        enabled: false
      master:
        persistence:
          enabled: true
          size: 2Gi
