apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - authentik-secrets.externalsecret.yaml   # secret_key + postgresql_password, from OpenBao
  - helmrepository.yaml
  - helmrelease.yaml
  - traefik-middleware.yaml
  - outpost-tls-certificate.yaml
