apiVersion: v1
kind: ConfigMap
metadata:
  name: geohazardwatch-config
  namespace: geohazardwatch
data:
  app-custom-config.json: |
    {
      "ngdpbase.server.host": "0.0.0.0",
      "ngdpbase.server.port": 3000,
      "ngdpbase.application.base-url": "https://geohazardwatch.com",
      "ngdpbase.application-name": "GeoHazardWatch",
      "ngdpbase.session.secure": true,
      "ngdpbase.session.sameSite": "lax",
      "ngdpbase.page.provider": "versioningfileprovider",
      "ngdpbase.theme.active": "volcano",
      "ngdpbase.front-page": "volcanoes-and-earthquakes",
      "ngdpbase.managers.addons-manager.addons-path": ["/app/addons", "/opt/geohazardwatch/addons"],
      "ngdpbase.addons.ve-geology.enabled": true,
      "ngdpbase.addons.ve-geology.dataPath": "/app/data/ve-geology"
    }
