apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: geohazardwatch
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - cronjob-import.yaml
  - image-policy.yaml
