apiVersion: v1
kind: Secret
metadata:
    name: yourphr-sandbox-credentials
    namespace: yourphr
type: Opaque
stringData:
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_ID: ENC[AES256_GCM,data:FGNJX0B89V3jM+CJ8m4+GWOZ1/ExDh+m+5Uv2RCOhSaTIN4Mwr24yA==,iv:ddJKkbpYXgJR1zrxwJlrzudbj7h6qfyViguYse27mR4=,tag:iTb0KWw4yjvcmglExiwhRA==,type:str]
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_SECRET: ENC[AES256_GCM,data:sNsV4BTu3ugFLA1V/0ioxkwHxGP6RR2u0x0HkKSuyia2UpQ0WuXHLtlryxvk23xijDRrf5+qX6GgVAsGnnCteFHByg/gMw5Ap8l9EZQMCl6b8Vu+9kzCI7HiNX9FFKs+erwP2GWc9aKNx9u8bZhH/VLp9cIrDEbLezHNGYijo/Q=,iv:m+OJeIhBGK74QmB2ZSgZ4uqJ3EMPgPVCddsm3MRmVas=,tag:FzqTr+HZ145Gfx+aK3lPfw==,type:str]
    YOURPHR_SANDBOX_EPIC_CLIENT_ID: ENC[AES256_GCM,data:wYzXoqaanVz0u+WzjPHTRL/zFWHMtK+UzMSY4Pxlhhdsd5XO,iv:D00Z7NMtIGCNz/8uZNigOJmC3eQJg2+BykUgFp5mCpg=,tag:ihMGFw7p6uuGQkWg95oAvg==,type:str]
    YOURPHR_SANDBOX_ORACLE_CLIENT_ID: ENC[AES256_GCM,data:NUZhzxjqEaXMuTjla2E55Q/N1KNUKloy2epo7PmIZO/9ZLl+,iv:Cjdckps3cBakeMI6qPIg2huLOC4gtn3ssxIMetmPj3M=,tag:c7/TLhMS6/5mkriVYhTxjg==,type:str]
    YOURPHR_SANDBOX_ATHENA_CLIENT_ID: ENC[AES256_GCM,data:A9htrDhI7IX+FWWbn8PputVbVp4=,iv:goj9ed4pvBsSWpZ4ZKjMl36xtr9DGvspEJpYwNoWvaI=,tag:iPwJnPbvXeMRUcaVAwv4FA==,type:str]
    YOURPHR_SANDBOX_ATHENA_CLIENT_SECRET: ENC[AES256_GCM,data:Fbogcl3EX2k84z5+6xOeWL2DVluhXaq4xtIuClmXbgfEZvNrzZssdRW5XwZgPLSpk3h11o3hB5bNBxkn6GH9ow==,iv:cb6iGdH59m1RSBvK5+SVP0xKyOwwcdTvLCejYY9FTlU=,tag:NqQSw4s5bZcj5TmMF07RkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS3pYUGg0c0IzWGVDUFpx
            dTVscWpNbXBuYnkrR2NMcDZzcmZYeXl1ZFRvCmVwTi9aOFBITlFyMHJUNWJnS2Jy
            clVUdkJIUlcya003SDNhMkhMQmVQd3MKLS0tIFFMQ2VWdVMvT2RjdXREcjVrMUp3
            aEd1M3NKU0N5R2NNUzFQT0RpUXN3cEUK/mVaEQT+jxZUWQSfhyNEbml5kzNA9pqI
            A3aekC36eP4A8xrRuiQdFhrYZOeXllm72ibfEzMMtzm+zc/YLiDrFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T17:39:07Z"
    mac: ENC[AES256_GCM,data:75rMBKPEvrLlLm6IGIlXG1IdFc9GJXtnROLyPV9e9uuK53iMr0azfgV7RulSGU7naj5Mp3uF1vMlbRTJBZ1Fp9zftW9YJx8+3sxvmUx0BddNW0k1sw1z2znHWoA5l7yDVDMaSjeGawsx/NmQpQ/Ll+DvwQOZgPG9sEImjdbytwE=,iv:q1TB04ejipKLfDavV+v7ZcTFGS49T+sOfZjp8j9gYw8=,tag:pyXwMVN9FmwODAta2GKg4w==,type:str]
    version: 3.13.1
