apiVersion: v1
kind: Secret
metadata:
    name: yourphr-sandbox-credentials
    namespace: yourphr
type: Opaque
stringData:
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_ID: ENC[AES256_GCM,data:iwHeWuFmgPnyEA+rtItMbJ4m0BQJs/k/4zEuVmXBlogbrksb86Q+qw==,iv:C2zl+8ZiXs0TawhxoIGI4IXGDPKIBHpwtRV2oWYvy4Q=,tag:bViPtqdPA/QkrADJqvkJNg==,type:str]
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_SECRET: ENC[AES256_GCM,data:IugNyWiBavU9YBGEkc5qbS5veBRB9OhRhBhh30pylp7yLX2wECkIN2vpgr12uCxyR0u66hAb20l0ENi4yuQi13/CptAcC9njqxJxkiB8EZNVDKCYGbZJg6gbJev6v/4lsgptpNQ8lKZ/7JRcuzmgUYERk00cHoO+GG1SXrZhdg0=,iv:9HFEqjsyY/4OH18PTFG0Z9N4eybI5I3q2NZLnqkvbzc=,tag:ERyHteN77Q/Fmnq00W4rzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIelhpZXl4bUJMM1l6a3Bm
            Y3Z0QmtsakJDRzF0MTNzQTM3ODU4SWRlSGlFCjk4NzRRWHpMa29IcmRzWFFyRFVp
            dllYM3hWcEVYL3o2VUlwVXlzRFpROXcKLS0tIENISzdkbUlHYkRzQW5CRDJhZ2ll
            bmQ1NU5OTy94MmRBcUxLYmlSRU10QzQKfi07JZCf3+r+9wCl7skiIYQK8Hiw2qlt
            NIE4Vp7AyBOvSfO+r+dvzagrddYjOAVrZ+z8ezolXmrrWam4aT0uLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T12:04:14Z"
    mac: ENC[AES256_GCM,data:U+UGln/hKtjV+GYfFkBZt6achNQ5HRmGOYzKWnQKM7Vk+MJuDMmu7RGqXNq0eb3bf653xQCQH+06MIUYJoiBbKrOC9uoex4lCHuVS3uA5IpG+mtAF8/chnj196feEgPrODYIZgs4K/IhWboUXuHFYBHg2lgpJ57NSgo07hSDatM=,iv:3RxDhxl8CjkYCtmQwkecKif0uFb6a6nLHw79EzOJDc4=,tag:P9LRYj72uwdCUtr2NzzSIA==,type:str]
    version: 3.13.1
