apiVersion: v1
kind: Secret
metadata:
    name: yourphr-sandbox-credentials
    namespace: yourphr
type: Opaque
stringData:
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_ID: ENC[AES256_GCM,data:+Iy7HK8ev5UlP5AwtQ4MMftYBZ1Te5c0dJ4++vhIW4dornzfM42scA==,iv:rkI/SbTgZCEDpB/Jx2KJ2nEhzTjgtgxLL90D5ZOILSU=,tag:dGLxkOH666yVO1ONrOVgpg==,type:str]
    YOURPHR_SANDBOX_BLUEBUTTON_CLIENT_SECRET: ENC[AES256_GCM,data:cJeLHpK3agyJAV4hFO52gvK5e9yCTnunq2FXqSdln9POTQ3iC4Ymaghi89USjKJ+jpKeMIAo4s9ggPAiecHqcxCbRVlmZb8ZfNwTms40EA+twaHm1OZGfphB64bp+D55cHLQ6tfKf2UVgNDRFGXVxNsqlgzy9sFxx0Xq4zh78W0=,iv:XghlOunUQSoatqtXBtuR7b+M2TE4ZP88NQ40fuOvI4U=,tag:ENpPCJhuCC/PxzGEZMz0CQ==,type:str]
    YOURPHR_SANDBOX_EPIC_CLIENT_ID: ENC[AES256_GCM,data:iqDQkNkrX2gwBY35lqDz2oj+ACd3hnuTL3mQvp/MWw3aZ0jQkdZP7G4jHOKo1AjDGRa7TcPTGw==,iv:3eSs3N6x2WjB6lHBkZonDOuMrAlqtzlWgTWuauhg6rs=,tag:7nIBWruigzG+VYmtxFf1UQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbjkyQ2NNZ1lmZjYzL0VZ
            d3RYZ1Q3TVZLajJyZjRwOTQ1U254cFVVSTNJClpzRW15NERYRGQ5VVNRQ1NKRHFU
            WFFveExKREFaZnpwa2pTamJLelZ5NjgKLS0tIFFiTyt3ZFZIY1VoQ2NSMThQMThk
            Rkh6NitzT09IM3o1cGwxV1ppaFBnMWsKdY4Y2fJHbQJIYyRgjtbioDjRBdfiZnaf
            HrJqI8YoSPYIvCFOt9giyzpaTUbyooSvkEF7PV3XQvjQDVUV02s3oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sr8j9p87wuuqfnmharzqqnwj76yyc6mu5j3r5t7sr3j88wzn8exqwy6jhj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T10:28:48Z"
    mac: ENC[AES256_GCM,data:w9GtW6aXPQwOx15YwNIYfyU2yTVyo+Cgxuv5j/XzlQ13mmVawuS7XxzBkQr/zMtRH5dsHT4z+PnHfUD5xTyDWrQ9duPDeB6I83RcQUQpxM5wwlXDpP6BkfcAteBG04sUPsd0bn2ecaI8dBIGKA9nVGDUbSztvbv5zzfznAmcU50=,iv:22IfPAtl70WZEd5sHiWgWlRIf+JkT3Sk7oRUg3oLGYE=,tag:8Gm6IsQyLGFQzXDjNn6y3g==,type:str]
    version: 3.13.1
