apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info

    common:
      path_prefix: /loki
      replication_factor: 1
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      ring:
        kvstore:
          store: inmemory
      instance_addr: 127.0.0.1

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:
      retention_period: 30d
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
      allow_structured_metadata: true
      max_label_name_length: 1024
      max_label_value_length: 4096

    compactor:
      working_directory: /loki/compactor
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 100
      delete_request_store: filesystem

    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/rules-tmp

    analytics:
      reporting_enabled: false
