apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
type: Opaque
stringData:
  # IMPORTANT: Change this password in production!
  # This is a temporary password for initial setup
  postgres-password: "changeme_secure_password_here"

  # Database passwords for applications
  teslamate-password: "teslamate_db_password_changeme"
