apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    app: postgresql
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    # Using local disk copy of data structure for proper permissions
    # NFS doesn't support chown needed by PostgreSQL
    path: /mnt/local-k3s-data/postgresql
    type: DirectoryOrCreate
